default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: tweakster
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tweakster_development

test:
  <<: *default
  database: tweakster_test
